views.py
import functools
from sqlite3 import Error
from flask import blueprints, render_template, request, session, flash
from flask.helpers import flash, url_for
from werkzeug.utils import redirect
from forms import *
from conn import conn, closeConn
from werkzeug.security import check_password_hash, generate_password_hash

main= blueprints.Blueprint("main", __name__)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if "usuario" not in session:
            return redirect(url_for("main.inicio"))
        return view(**kwargs)
    return wrapped_view

def login_estudiante(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if session["rol"] != "Estudiante":
            return redirect(url_for("main.inicio"))
        return view(**kwargs)
    return wrapped_view

def login_profesor(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if session["rol"] != "Profesor":
            return redirect(url_for("main.inicio"))
        return view(**kwargs)
    return wrapped_view

def login_administrador(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if session["rol"] != "Administrador":
            return redirect(url_for("main.inicio"))
        return view(**kwargs)
    return wrapped_view

@main.route("/", methods=["GET", "POST"])
def inicio():
    form = FormInicio()
    
    if (form.validate_on_submit()):
        usuario=request.form["usuario"]
        contrasena=request.form["contrasena"]
        db=conn()
        usuarioConsulta = db.execute("select * from login where user = ?", (usuario,)).fetchone()
        db.commit()

        if usuarioConsulta is not None:
            contrasena = contrasena + usuario + "Surcolombiana"
            sw = check_password_hash(usuarioConsulta[1], contrasena)        
            if(sw):
                if(usuarioConsulta[2] == "Estudiante"):
                    session["usuario"]=usuarioConsulta[0]
                    session["rol"]=usuarioConsulta[2]
                    closeConn()
                    return (notasestudiante())
                if(usuarioConsulta[2] == "Profesor"):
                    session["usuario"]=usuarioConsulta[0]
                    session["rol"]=usuarioConsulta[2]
                    closeConn()
                    return (administrarCursosProfesor())
                if(usuarioConsulta[2] == "Administrador"):
                    session["usuario"]=usuarioConsulta[0]
                    session["rol"]=usuarioConsulta[2]
                    closeConn()
                    return (busquedasadmin())
            else:
                flash("Contraseña incorrecta")
        if usuarioConsulta is None:
            flash("Usuario incorrecto")

    return render_template("index.html", form=form)



@main.route("/adminAdministraMaterias/", methods=["GET", "POST"])
@login_required
@login_administrador
def adminAdministraMaterias():

    formularioAgregarEstudiante = FormAgregarEstudiantesCrearMateria()
    formularioRemoverEstudiante = FormRemoverEstudiantesCrearMateria()

    if (formularioAgregarEstudiante.validate_on_submit()):
        estudiante = request.form["codigoEstudianteAgrega"]
        materia = request.form["nombreMateria"]
        
        queryActualizacion = "insert into alumnosmaterias(nombreMateria, idAlumno) values (?,?) "
                
        try:
            db = conn()
            valoresParaActualizar = (materia, estudiante)
            db.execute(queryActualizacion,valoresParaActualizar)
            db.commit()
            
        except Error:
            print(Error)
    
    if (formularioRemoverEstudiante.validate_on_submit()):
        estudiante = request.form["codigoEstudianteRemueve"]
        materia = request.form["nombreMateria"]
        queryConsulta = "delete from alumnosmaterias where idAlumno = ? and nombreMateria LIKE ?"
        valoresABorrar = (estudiante, materia)
        try:
            db = conn()
            db.execute(queryConsulta, valoresABorrar)
            db.commit()
            
        except Error:
            print(Error)


    return render_template("adminAdministraMaterias.html", formularioAgregarEstudiante=formularioAgregarEstudiante, formularioRemoverEstudiante=formularioRemoverEstudiante)


@main.route("/administrarCursosProfesor/")
@login_required
@login_profesor
def administrarCursosProfesor():
    flash(session["usuario"])
    return render_template("administrarCursosProfesor.html")
    

@main.route("/adminRegistro/", methods=["GET", "POST"])
@login_required
@login_administrador
def adminRegistro():
    form = FormRegistrarUsuario()
    if (form.validate_on_submit()):
        nombre= request.form["nombre"]
        apellido= request.form["apellido"]
        codigo= request.form["codigo"]
        telefono= request.form["telefono"]
        correo= request.form["correo"]
        rol= request.form["rol"]
        usuario= request.form["usuario"]
        contrasena= request.form["contrasena"]
        contrasena= contrasena + usuario + "Surcolombiana"
        contrasena = generate_password_hash(contrasena)

        valoresAIngresar=(usuario,contrasena,rol)
        query="insert into login(user, password, rol)values(?,?,?)"
        try:
            db = conn()
            db.execute(query, valoresAIngresar)
            db.commit()
            print("Usuario Ingresado a login")
            
        except Error:
            print(Error)    
        
        if (rol == "Estudiante"):
            try:
                valoresAIngresar=(codigo, nombre, apellido, correo, telefono, usuario)
                query="insert into alumnos(id_alumno,nombre,apellido,correo,telefono,user)values(?,?,?,?,?,?)"
                db.execute(query, valoresAIngresar)
                db.commit()
                print("Usuario Ingresado a alumnos")
                closeConn()
            except Error:
                print(Error)
        
        if (rol == "Profesor"):
            try:
                valoresAIngresar=(codigo, nombre, apellido, correo, telefono, usuario)
                query="insert into profesores(id_profesor,nombre_p,apellido_p,correo_p,telefono_p,user)values(?,?,?,?,?,?)"
                print(query, valoresAIngresar)
                db.execute(query, valoresAIngresar)
                db.commit()
                print("Usuario Ingresado a profesor")
                closeConn()
            except Error:
                print(Error)
    return render_template("adminRegistro.html", form=form)


@main.route("/busquedasadmin/")
@login_required
@login_administrador
def busquedasadmin():
    return render_template("busquedasadmin.html")


@main.route("/creareditaractiv/", methods=["GET", "POST"])
@login_required
@login_administrador
def creareditaractiv():
    form = FormCrearActividad()
    if (form.validate_on_submit()):
        return ("ACTIVIDAD CREADA")
        ### Se debe actualizar la lista con las actividades, y salir alerta de actividad creada
    return render_template("creareditaractiv.html", form=form)


@main.route("/creareditaractivProfesor/", methods=["GET", "POST"])
@login_required
@login_profesor
def creareditaractivProfesor():
    flash(session["usuario"])
    form = FormCrearActividad()
    if (form.validate_on_submit()):
        nombreActividad = request.form["nombreActividad"]
        descricionActividad = request.form["descripcion"]
        materia= request.form["materia"]
        query="INSERT into actividades(nombre_actividad,descripcion, nombreMateria) VALUES(?,?,?);" 
        valoresAIngresar =(nombreActividad,descricionActividad, materia)
        try:
            db = conn()
            db.execute(query, valoresAIngresar)
            db.commit()

        except Error:
            print(Error)
        ###Debe retornar alerta de actividad creada
    return render_template("creareditaractivProfesor.html", form= form)


@main.route("/crearMateria/", methods=["GET", "POST"])
@login_required
@login_administrador
def crearMateria():
    formularioCrearMateria = FormCrearMateria()
    if (formularioCrearMateria.validate_on_submit()):
        nombreMateria = request.form["nombreMateria"]
        profesorMateria= request.form["profesorMateria"]
        query="INSERT into materias(nombre_materia,id_profesor) VALUES(?,?);" 
        valoresAIngresar=(nombreMateria,profesorMateria)

        try:
            db = conn()
            db.execute(query, valoresAIngresar)
            db.commit()
        except Error:
            print(Error)
    return render_template("crearMateria.html",  formularioCrearMateria=formularioCrearMateria)


@main.route("/detalleactividadAdmin/")
@login_required
@login_administrador
def detalleactividadAdmin():
    return render_template("detalleactividadAdmin.html")


@main.route("/detalleActividadEstudiante/")
@login_required
@login_estudiante
def detalleActividadEstudiante():
    return render_template("detalleActividadEstudiante.html")


@main.route("/creareditaractivProfesor/detalleactividadProfesor/<string:actividad>/", methods=["GET","POST"])
@login_required
@login_profesor
def detalleactividadProfesor(actividad):
    flash(actividad)
    form = CalificarActividad()
    if (form.validate_on_submit()):
        codigoEstudiante= request.form["idAlumno"]
        nota = request.form["nota"]
        idActividad = actividad
        retroalimentacion = request.form["retroalimentacion"]
        query = "insert into actividadesPorAlumnos(idAlumno,idActividad,nota,retroalimentacion)values(?,?,?,?)"
        valoresAInsertar = (codigoEstudiante,idActividad,nota,retroalimentacion)
        try:
            db = conn()
            db.execute(query, valoresAInsertar)
            db.commit()
        except Error:
            print(Error)



    return render_template("detalleactividadProfesor.html", form=form)





@main.route("/informacionestudiante/", methods=["GET", "POST"])
@login_required
@login_estudiante
def informacionestudiante():
    flash(session["usuario"])

templates/adminAdministraMaterias.html
{% extends "baseAdmin.html" %}

{% block section %}



<section class="sectionPrincipales">
    
    <script src="{{url_for('static', filename='js/ajaxlistaEstudiantes.js')}}"></script>
    
            
    <h1>ADMINISTRAR MATERIAS</h1>

    <h1 class="buttonPequeño">MATERIAS</h1>

    <div id="listaMaterias">

    </div>

    <div class="cajaMaterias">
        <div class="botonCrearMateriaDesdeAdmin">
            <a href= ../crearMateria ><button class="buttonPequeño">Crear Materia</button></a>
        </div>
        
        
        <div id="contenedorParaMaterias">
            <div class="contenedorMateria">
                <div class="materia">
                    
                    <p id= "nombreMateriaAdministrarMateria">Nombre materia</p>
                    
                    <div class="listaEstudiantes" id="listaParaLlenarEstudiantes">
                    </div>
                    <div>
                        <form method="post"class="contenedorFormQuitaYAgrega">
                        {{formularioAgregarEstudiante.hidden_tag()}}
                        {{formularioAgregarEstudiante.nombreMateria(id="nombreMateriaAdministrarMateria2")}}
                        {{formularioAgregarEstudiante.codigoEstudianteAgrega(class="campoIdAgregarEstudiante")}}
                        {{formularioAgregarEstudiante.agregarEstudiante(class="botonAgregarRemoverEstudiante")}}
                        </form>
                    </div>
                    <div>
                        <form method="post"  class="contenedorFormQuitaYAgrega">
                        {{formularioRemoverEstudiante.hidden_tag()}}
                        {{formularioRemoverEstudiante.nombreMateria(id="nombreMateriaAdministrarMateria3")}}
                        {{formularioRemoverEstudiante.codigoEstudianteRemueve(class="campoIdAgregarEstudiante")}}
                        {{formularioRemoverEstudiante.removerEstudiante(class="botonAgregarRemoverEstudiante")}}
                        </form>
                    </div>

                    
                </div>
                <div class="estado">
                    <a href= ../creareditaractiv ><button class="buttonPequeño">Crear/Editar Actividades</button></a>
                    
                </div>
                <div class="profesor">
                    <p>Profesor</p>
                    <p id="nombreProfeConsultarMateria">Nombre Profesor</p>
                    <img src="{{url_for('static', filename='img/fofoUsuario.png')}}" alt="Imagen Profesor" class="imgPequenaProfesor">
                
                </div>
            </div>
        </div>



    </div>

</section>


{% endblock %}

templates/administrarCursosProfesor.html
{% extends "baseProfesor.html" %}

{% block section %}
<script src="{{url_for('static', filename='js/ajaxProfe.js')}}"></script>

<section class="sectionPrincipales">

    <h1>ADMINISTRAR CURSOS</h1>

    <h1 class="buttonPequeño">MATERIAS</h1>
    <p class="pConBorde" id="nombreProfeMateria"></p>

    <div id="listaMaterias">

    </div>
    
    <div class="contenedorAdminCursosProfe">
        <div class="contenedorMateriaAdminCursosProfe">
            <div class="columnaUnoContMaterAdminCursosProfe">
                <p class="pConBorde" id="nombreMateriaAdministrarMateria">Nombre de Materia </p>
                <div class="listaEstudiantes" id="listaParaLlenarEstudiantesProfe">
                </div>                      
            </div>

            <div class="estado">
                <a href= {{url_for("main.creareditaractivProfesor")}} ><button class="buttonPequeño">Crear/Editar Actividades</button></a>
                
            </div>


        </div>

    </div>

</section>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/normalize.css' )}} " >
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@500&display=swap" rel="stylesheet">

</head>

    {% block content %}

    {% endblock %}

</html>

templates/baseAdmin.html
{% extends "base.html" %}

{% block title %} Administrador {% endblock %}

{% block content %}


<body class="bodyPrincipales">

    <aside class="asidePrincipal">
        <div class="asideSuperior">
            <img src="{{url_for('static', filename='img/fofoUsuario.png')}}" alt="fotoUsuario" class="fotoUsuario">
            <h1 class="usuarioAside">Admin</h1>
            <button class="button"> <a href= {{url_for("main.salir")}} style="color: white;"> Salir </a></button>
            
        </div>
        <div class="asideInferior">
            <h1>PANEL DE NAVEGACION</h1>

            <a href= {{url_for("main.adminAdministraMaterias")}} >Administrar materias</a>
            <a href= {{url_for("main.busquedasadmin")}}>Buscar/Editar Información</a>
            <a href= {{url_for("main.adminRegistro")}} >Registro</a>

            <button class="button"><a href="{{url_for("main.preguntas")}}" style="color: white;">FAQ</a></button>
            <button class="button">Reportar Error</button>
        </div>
    
    </aside>

    <div>
        <header class="headerPrincipales">
            <div class="tituloHeader">
                <h1>PLATAFORMA SURCO - ADMIN</h1>
            </div>
            <img src="{{url_for('static', filename='img/logodef.png')}}" alt="logo universidad" class="imgPrincipales">
        </header>

        {% block section %}

        {% endblock %}


    </div>
</body>




{% endblock %}

templates/baseEstudiante.html
{% extends "base.html" %}

{% block title %} Estudiante {% endblock %}

{% block content %}


<body class="bodyPrincipales">

    <aside class="asidePrincipal">
        <div class="asideSuperior">
            <img src="{{url_for('static', filename='img/fofoUsuario.png')}}" alt="fotoUsuario" class="fotoUsuario">
            <h1 class="usuarioAside" id="rolPagina">Estudiante</h1>
            {% for message in get_flashed_messages() %}
            <div class="flashRol">
                <p id="flashRolP">{{message}}</p>
            </div>
            {% endfor %}
            <button class="button"> <a href= {{url_for("main.salir")}} style="color: white;"> Salir </a></button>
            
        </div>
        <div class="asideInferior">
            <h1>PANEL DE NAVEGACION</h1>

            <a href= {{url_for("main.notasestudiante")}} >Ver Notas</a>
            <a href= {{url_for("main.informacionestudiante")}} >Ver información</a>

            <button class="button"><a href="{{url_for("main.preguntas")}}" style="color: white;">FAQ</a></button>
            <button class="button">Reportar Error</button>
        </div>
    
    </aside>

    <div>
        <header class="headerPrincipales">
            <div class="tituloHeader">
                <h1>PLATAFORMA SURCO - ESTUDIANTE</h1>
            </div>
            <img src="{{url_for('static', filename='img/logodef.png')}}" alt="logo universidad" class="imgPrincipales">
        </header>

        {% block section %}

        {% endblock %}


    </div>
</body>





{% endblock %}

templates/baseProfesor.html
{% extends "base.html" %}

{% block title %} Profesor {% endblock %}

{% block content %}


<body class="bodyPrincipales">

    <aside class="asidePrincipal">
        <div class="asideSuperior">
            <img src="{{url_for('static', filename='img/fofoUsuario.png')}}" alt="fotoUsuario" class="fotoUsuario">
            <h1 class="usuarioAside" id="rolPagina">Profesor</h1>
            {% for message in get_flashed_messages() %}
            <div class="flashRol">
                <p id="flashRolP">{{message}}</p>
            </div>
            {% endfor %}
            <button class="button"> <a href= {{url_for("main.salir")}} style="color: white;"> Salir </a></button>
            
        </div>
        <div class="asideInferior">
            <h1>PANEL DE NAVEGACION</h1>

            <a href= {{url_for("main.administrarCursosProfesor")}} >Administrar materias</a>
            <a href= {{url_for("main.informacionprofesores")}} >Ver Información</a>

            <button class="button"><a href="{{url_for("main.preguntas")}}" style="color: white;">FAQ</a></button>
            <button class="button">Reportar Error</button>
        </div>
    
    </aside>

    <div>
        <header class="headerPrincipales">
            <div class="tituloHeader">
                <h1>PLATAFORMA SURCO - PROFESOR</h1>
            </div>
            <img src="{{url_for('static', filename='img/logodef.png')}}" alt="logo universidad" class="imgPrincipales">
        </header>

        {% block section %}

        {% endblock %}


    </div>
</body>




{% endblock %}

templates/busquedasadmin.html
{% extends "baseAdmin.html" %}

{% block section %}

<section class="sectionPrincipales">
    
    <h1>VER REGISTRO</h1>
    <p></p>
    
    <div class="contenedorAdminCursosProfe">
        <div class="contenedorMateriaAdminCursosProfe">

            
        <table class="default">

            <tr>
        
            <td><p class="pConBorde">Rol</p></td>
        
            <td><p class="pConBorde">Nombre</p></td>
        
            <td><p class="pConBorde">Apellido</p></td>

            <td><p class="pConBorde">Código</p></td>
            <td><p class="pConBorde">Teléfono</p></td>
            <td><p class="pConBorde">Correo</p></td>
        
            </tr>
        
            <tr>
        
                <td>Estudiante</td>
            
                <td>Armando</td>
            
                <td>Pereque</td>
                <td>2001001</td>
            
                <td>57 000 000 0000</td>
            
                <td>armando.pereque@estudiante.com</td>
        
            </tr>

            <tr>
        
                <td>Estudiante</td>
            
                <td>Armando</td>
            
                <td>Pereque</td>
                <td>2001001</td>
            
                <td>57 000 000 0000</td>
            
                <td>armando.pereque@estudiante.com</td>
            
            </tr>

            <tr>
        
                <td>Estudiante</td>
            
                <td>Armando</td>
            
                <td>Pereque</td>
                <td>2001001</td>
            
                <td>57 000 000 0000</td>
            
                <td>armando.pereque@estudiante.com</td>
            
            </tr>

            <tr>
        
                <td>Profesor</td>
            
                <td>Elkin</td>
            
                <td>Tosueño</td>
                <td>0000001</td>
            
                <td>57 000 000 0000</td>
            
                <td>elkin.tosueño@estudiante.com</td>
            
            </tr>
            <tr>
        
                <td>Profesor</td>
            
                <td>Elkin</td>
            
                <td>Tosueño</td>
                <td>0000001</td>
            
                <td>57 000 000 0000</td>
            
                <td>elkin.tosueño@estudiante.com</td>
            
            </tr>
        
        </table>

    </div>
    <div class="contenedorMateriaAdminCursosProfe">
        
        <p class="pConBorde"></p>
        
        <p><button class="button">BUSCAR</button></p>
        
        <p><button class="button">EDITAR</button></p>
        <p></p>
        <p></p>
        <p></p>
    </div>
        <div class="contenedorMateriaAdminCursosProfe">
                
        <p><button class="button">EDITAR NOTAS COHORTE</button></p>
        <p><img src="url_for('static', filename='img/candadoCerrado.png')" alt="Candado cerrado" class="imgEstadoMateria"></p>
        
        </div>
        
</div>
    
</section>

{% endblock %}

templates/creareditaractiv.html
{% extends "baseAdmin.html" %}

{% block section %}


<section class="sectionPrincipales">

    <h1>CREAR/EDITAR ACTIVIDADES</h1>
    <form action="" name="formularioEditarActividad" id="formularioEditarActividad">

        <div class="cajaSuperiorEditarActiv">
            <div class="contenedorDescripcionMateria">
                <p>Nombre de Curso</p>
                <p class="pConBorde">Fisica I</p>
                <p>Cupo</p>
                <p class="pConBorde">35</p>
                <p>Profesor</p>
                <p class="pConBorde">35</p>
            </div>
            <div class="contenedorActividadesEditar">
                <div></div>
                <input type="text" name="actividadUno" placeholder="Actividad1" class="pConBorde">
                <input type="text" name="actividadDos" placeholder="Actividad2" class="pConBorde">
                <input type="text" name="actividadTres" placeholder="Actividad3" class="pConBorde">
                <input type="text" name="actividadCuatro" placeholder="Actividad4" class="pConBorde">
            </div>
            <div class="contenedorNotasEditar">
                <p>PORCENTAJE DE NOTA FINAL</p>
                <input type="text" name="porcentajeActividadUnoEditar" placeholder="25%" class="pConBorde">
                <input type="text" name="porcentajeActividadUnoEditar" placeholder="25%" class="pConBorde">
                <input type="text" name="porcentajeActividadUnoEditar" placeholder="25%" class="pConBorde">
                <input type="text" name="porcentajeActividadUnoEditar" placeholder="25%" class="pConBorde">
            </div>
            <div class="contenedorVerDetallesEditar">
                <p>Ver detalles</p>
                <a href=""><img src="{{url_for('static', filename='img/imagenBloc.png')}}" alt="imagen Detalles" class="imagenBlocEditar"></a>
                <a href=""><img src="{{url_for('static', filename='img/imagenBloc.png')}}" alt="imagen Detalles" class="imagenBlocEditar"></a>
                <a href=""><img src="{{url_for('static', filename='img/imagenBloc.png')}}" alt="imagen Detalles" class="imagenBlocEditar"></a>
                <a href=""><img src="{{url_for('static', filename='img/imagenBloc.png')}}" alt="imagen Detalles" class="imagenBlocEditar"></a>
                
            </div>
            <div class="contenedorFechaEntregaEditar">
                <p>Fecha de entrega</p>
                <input type="text" name="fechaEntregaActividadUnoEditar" placeholder="05/11/2021" class="pConBorde">
                <input type="text" name="fechaEntregaActividadDosEditar" placeholder="05/11/2021" class="pConBorde">
                <input type="text" name="fechaEntregaActividadTresEditar" placeholder="05/11/2021" class="pConBorde">
                <input type="text" name="fechaEntregaActividadCuatroEditar" placeholder="05/11/2021" class="pConBorde">
            </div>
        </div>
        <div class="cajaMediaEditarActiv">
            <input type="submit" class="buttonPequeño" value="Editar" id="botonEditarActividad">
            <button class="buttonPequeño">+</button>
            <p>Total</p>
            <p class="pConBorde">100%</p>
            <div></div>
        </div>
    </form>

    <form action="" name="formularioCrearActividad" id="formularioCrearActividad">
        {{form.hidden_tag()}}
        <div class="cajaInferiorEditarActiv">
            <div class="contenedorIzquierdoCajaInferiorEditarActiv">
                <p>Nombre de Actividad</p>
                {{form.nombreActividad}}
                <p>Fecha de Inicio</p>
                {{form.fechaDeInicio}}
                <p>Fecha de Cierre</p>
                {{form.fechaDeCierre}}
            </div>
            <div class="contenedorDerechoCajaInferiorEditarActiv">
                <p>Descripción</p>
                    {{form.descripcion}}
            </div>
        </div>
        <input type="submit" class="buttonPequeño" value="Guardar" id="botonGuardarCrearActividad">
    </form>

    

</section>


{% endblock %}

templates/detalleActividadEstudiante.html
{% extends "baseEstudiante.html" %}

{% block section %}


<section class="sectionPrincipales">

    <h1>DETALLE DE ACTIVIDAD</h1>

    <div class="contenedorDetalleActividad">

        <div class="contenedorDetalleActividadIzquierdo">
            <p>Nombre de Actividad</p>
            <p class="pConBorde">Actividad1</p>
            <p>Materia</p>
            <p class="pConBorde">Física 1</p>
            <p>Profesor</p>
            <p class="pConBorde">Nombre Profesor</p>
            <p>Fecha de Inicio</p>
            <p class="pConBorde">13/03/2021</p>
            <p>Fecha de Cierre</p>
            <p class="pConBorde">05/11/2021</p>
            <p>Correo de entrega</p>
            <p class="pConBorde">correo@profesor.com</p>

        </div>
        <div class="contenedorDetalleActividadDerecho">
            <p>Descripción:</p>
            <p class="pConBorde">El estudiante debe entregar módulo 1 resuelto en formato pdf al correo</p>

        </div>
    </div>
    

</section>



        

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block title %} Sistema de administración de notas {% endblock %}

{% block content %}
<body>
    

    <header>
        <div id="logo">
            <img src="{{url_for('static', filename='img/logodef.png')}}" alt="logo universidad">
        </div>
    </header>
    <section>
        <div id="captcha">
        </div>
        <form id="login" name="login" method="post" action="">
            {{form.hidden_tag()}}
            <div id="userName" class="camposLogin">
                {{form.usuario(size=30, placeholder="Usuario")}}
            </div>
            <div id="password" class="camposLogin">
                {{form.contrasena(size=30, placeholder="Contraseña")}}
            </div>
            {% for message in get_flashed_messages() %}
            <div class="mensaje">
                <p> {{message}} </p>
            </div>
            {% endfor %}
            <div id="recordarContrasena">
                <a href="">¿Olvidó su contraseña?</a>
            </div>
            <div id="btnLogin">
                {{form.enviar()}}
            </div>


        </form>
    </section>
    <footer>

    </footer>

</body>


{% endblock %}